### PR TITLE
Fix #5

### LINKED ISSUE #5: Implement a 'feedback' search field
Together with [adding a 'score' search field](https://github.com/ArtOfCode-/Sentinel/issues/4), it would be convenient to have a way to search posts having a certain feedback. For example, one use-case would be returning all the posts above a certain score that Natty incorrectly reported and were given a `fp` feedback: this would enable to enhance the bot and tweak it further.

As one post can have multiple conflicting feedback, there are several ways to make this happen:

 - Search on a global "mean" feedback. If there are more `tp` than `fp`, consider the post as `tp`, likewise for `fp`, but this wouldn't handle the case where they are in an equal number.
 - Search on whether it has at least one of the given feedback. If I search for `tp`, I would be presented with all posts having at least one feedback as `tp`.

The 2nd implementation would be more reasonable for the proposed use-case, and far easier to understand.

### PR DESCRIPTION
**Pull request by Fortunate-MAN**
Fixes #5.

Only feedback search:

screen shot 2018-04-01 at 11 57 05 am

Feedback + Search term:

screen shot 2018-04-01 at 11 57 39 am

I've implemented the first suggestion in the issue.

### CODE REVIEW

**Comment by Fortunate-MAN** [comment]
Could someone review this before merging? I had some weird behaviour originally, but it seemed all fine later.

**Comment by Fortunate-MAN** [comment]
Implemented #4 now.

screen shot 2018-04-01 at 2 37 36 pm

File: app/controllers/search_controller.rb [hunk 1]
```diff
@@ -6,6 +6,25 @@ def results
     @results = Post.where('title LIKE ?', "%#{search_term}%")
                .or(Post.where('body LIKE ?', "%#{search_term}%"))
                .or(Post.where('username LIKE ?', "%#{search_term}%"))
+
+    case params[:feedback]
+    when "true positive"
+      feedback = 1
```
Comment (ArtOfCode-) [inline app/controllers/search_controller.rb]: These aren't guaranteed to always be the correct IDs - put them in the select tag instead and use that to send them across

Comment (Fortunate-MAN) [reply app/controllers/search_controller.rb]: Hmm, makes sense. Thanks! I'll make the change right away.

File: app/controllers/search_controller.rb [hunk 2]
```diff
@@ -7,18 +7,9 @@ def results
...
-    when "true negative"
-      feedback = 3
-    when "needs edit"
-      feedback = 4
-    end
-
-    if feedback.present?
+    feedback = params[:feedback]
+    if feedback.present? && feedback != "-1" # -1 signifies no specific feedback is selected.
+      feedback.to_i
```
Comment (Fortunate-MAN) [inline app/controllers/search_controller.rb]: FYI, I didn't use `to_i` when initialising `feedback` because it seemed to never work with the "Any" option selected, even though it worked in the rails console. I'm guessing it must be some silly error, but it doesn't really matter as string comparisons work just as well.

File: app/views/search/results.html.erb [hunk 3]
```diff
@@ -7,6 +7,22 @@
       <%= submit_tag 'Search', :class => "btn btn-success" %>
     </span>
   </div>
+  <br/>
+  Feedback type
+  <div class="field input-group">
+    <%= select_tag 'feedback', options_for_select([["Any", ""], ["true positive", 1], ["false positive", 2], ["true negative", 3], ["needs edit", 4]], params[:feedback]), :class => "form-control" %>
```
Comment (ArtOfCode-) [inline app/views/search/results.html.erb]: Not quite what I meant. You want something like `options_from_collection_for_select(FeedbackType.all, 'id', 'short_code')` and use the `include_blank: true` option to `select_tag`. Then you can test for `params[:feedback].present?` in the controller.

**Comment by Fortunate-MAN** [comment]
@ArtOfCode- done.
